twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joy:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 10
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 5
